### ISSUE TITLE
Ultimate Bags Stack

### ISSUE THREAD

**Issue by Wxrlds** [Tfarcenim/InfinityStorage#1]
I don't know if this is intended but Ultimate Bags Stack in your inventory
![grafik](https://user-images.githubusercontent.com/42120270/63171184-4ed9a280-c03b-11e9-88fd-cdb6331b5511.png)

**Comment by Tfarcenim** [comment]
that is a bit of an issue as that will lead to dupe bugs easily, I will fix in a bit

**Comment by Tfarcenim** [comment]
fixed
