### ISSUE TITLE
Item name for Ultimate Chest is wrong

### ISSUE THREAD

**Issue by Wxrlds** [Tfarcenim/InfinityStorage#2]
The ingame name for the Infinity Chest is "tile.infinitystorage:ultimate_chest.name"

The lang file which is included in the mod says this:
`tile.infinitystorage:ultimate_bag.name=Infinity Chest`
but it has to be
`tile.infinitystorage:ultimate_chest.name=Infinity Chest`

**Comment by Tfarcenim** [comment]
fixed
